### ISSUE TITLE
The benchmarks do not execute anmore

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr-benchmark#1]
<img width="1152" alt="Screenshot 2019-07-12 at 02 19 28" src="https://user-images.githubusercontent.com/743833/61093833-abe6a500-a44c-11e9-9172-394bfb9d8bda.png">

**Comment by mincong-h** [comment]
@danieldietrich , it seems that the `runDebugWithAsserts` does not work as expected. After disabling it, the source code works fine. I suspect that this is related to fork count in general: `runDebugWithAsserts` implies `io.vavr.JmhRunner.ForkJvm.DISABLE` (forkCount=0). This makes JMH runner unhappy :( However, I'm not able to tell what's going on there...

```diff
public class JmhRunner {
    /**
     * Runs all the available benchmarks in precision mode.
     * Note: it takes about 3 hours.
     */
    public static void main(String[] args) {
        final Array<Class<?>> CLASSES = Array( ... );
-       runDebugWithAsserts(CLASSES);
        runSlowNoAsserts(CLASSES);
    }
```

Also, different from goal `exec:java`, goal `exec:exec` executes programs and Java programs in a separate process. I'm not sure if it can communicate to Maven Surefire about the result of assertions. Commenting the line I mentioned can be a good start to recover the entire disabled benchmark. WDYT?

**Comment by mincong-h** [comment]
If the method `runDebugWithAsserts` was supposed to verify the correctness of the code, I suggest splitting the launching logic into two parts: unit test and JMH. I can help on it.

**Comment by danieldietrich** [comment]
@mincong-h thank you for you analysis! Please remove runDebugWithAsserts (and all code that belongs to it), I never have been a friend of it. Once, there were assertions in the Vector impl only. They have been removed (at least I can't find them in the code anymore). The code should not contain any whitebox tests that check internal constraints.

Please go ahead :)

**Comment by mincong-h** [comment]
Thank you @danieldietrich , pull request sent #6
